a = open('HCN.INP')
A = a.read().split()
a.close()
A.pop(0)
A = [int(i) for i in A]
A = dict([(A[int(2 * i)], A[int(2 * i + 1)]) for i in range(int(len(A)/2))])
b = open('HCN.OUT', 'w+')
A1 = list(A)
A2 = list(A.values())
A1.sort()
A2.sort()
b.write(str(A1[0]) + ' ' + str(A2[-1]) + '\n')
b.write(str(A1[-1]) + ' ' + str(A2[0]))
b.close()